name: Update dependent packages


on:
  schedule:
    # UTC指定（JST12時に実行）
    - cron: '00 3 * * *'
  workflow_dispatch:

jobs:
  # NOTE: actions/cache@v2は手動でキャッシュを削除することができない。（キャッシュは7日保持）
  #       そのため「他のジョブでキャッシュを使いまわしたい」 + 「1フローでキャッシュを使い捨てしたい」場合は工夫が必要。
  #       実現方法はキャッシュのkeyに実行時のタイムスタンプをもたせて実行ごとにkeyが重複しないようにしている。
  # NOTE: outputsの値は子は参照できるが、孫は参照できない
  #       outputsが設定されたjobに依存するjobのみ参照可能。間接的に依存しているjobは参照不可
  #       依存していないjobで参照した場合は値を橋渡しする必要がある
  # NOTE: if 判定に${{}}は不要。if判定はjob名の直下に記述（これを満たさないと正常に動作しない）
  provision:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    # - name: Check the execution environment
    #   run: php -v

    - name: verify composer.json and composer.lock
      run: composer verify

  update:
    needs: provision
    runs-on: ubuntu-latest
    outputs:
      count: ${{ steps.changes.outputs.count }}
      timestamp: ${{ steps.changes.outputs.timestamp }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Update dependent packages
      run: composer update

    - name: Update check
      id: changes
      run: |
        git status
        echo "::set-output name=count::$(git status -s | wc -c)"
        echo "::set-output name=timestamp::$(date "+%s")"

    - name: Composer cache or restore
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: |
          vendor
          composer.json
          composer.lock
        key: ${{ runner.os }}-composer-${{ steps.changes.outputs.timestamp }}

  testing:
    if: 0 < needs.update.outputs.count
    runs-on: ubuntu-latest
    needs: update
    # 子へ継承するために親のoutputsをそのまま橋渡しする
    outputs:
      count: ${{ needs.update.outputs.count }}
      timestamp: ${{ needs.update.outputs.timestamp }}
    
    steps:
    - name: Debug Outputs # debug
      run: echo ${{needs.update.outputs.count}} ${{needs.update.outputs.timestamp}}

    - name: Checkout repository
      uses: actions/checkout@main

    - name: Composer cache or restore
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: |
          vendor
          composer.json
          composer.lock
        key: ${{ runner.os }}-composer-${{ needs.update.outputs.timestamp }}
        restore-keys: ${{ runner.os }}-composer-${{ needs.update.outputs.timestamp }}

    - name: Update check
      run: git status

    - name: Testing
      # run: php ./vendor/bin/phpunit
      run: make test

  commit:
    if: 0 < needs.testing.outputs.count
    runs-on: ubuntu-latest
    needs: testing

    steps:
    - name: Debug Outputs # debug
      run: echo ${{needs.testing.outputs.count}} ${{needs.testing.outputs.timestamp}}

    - name: Checkout repository
      uses: actions/checkout@main

    - name: Composer cache or restore
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: |
          vendor
          composer.json
          composer.lock
        key: ${{ runner.os }}-composer-${{ needs.testing.outputs.timestamp }}
        restore-keys: ${{ runner.os }}-composer-${{ needs.testing.outputs.timestamp }}

    - name: Update check
      run: git status
      
    - name: commit
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@example.com"
        git add composer.lock
        git commit -m 'update composer packages.'
        git push origin
